version: 1
update_configs:
  - package_manager: docker
    directory: /
    update_schedule: daily
    default_reviewers:
      - "syou6162"
  - package_manager: python 
    directory: /
    update_schedule: daily
    default_reviewers:
      - "syou6162"
